#!/bin/bash
stow -vD -t "$HOME"/ X11
stow -vD -t "$HOME"/ bat
stow -vD -t "$HOME"/ bottom
stow -vD -t "$HOME"/ broot
stow -vD -t "$HOME"/ dunst
stow -vD -t "$HOME"/ dwm
stow -vD -t "$HOME"/ flake8
stow -vD -t "$HOME"/ git
stow -vD -t "$HOME"/ htop
stow -vD -t "$HOME"/ lf
stow -vD -t "$HOME"/ mpv
stow -vD -t "$HOME"/ neofetch
stow -vD -t "$HOME"/ nvim
stow -vD -t "$HOME"/ polybar
stow -vD -t "$HOME"/ pycodestyle
stow -vD -t "$HOME"/ pylint
stow -vD -t "$HOME"/ ranger
stow -vD -t "$HOME"/ rofi
stow -vD -t "$HOME"/ shell
stow -vD -t "$HOME"/ starship
stow -vD -t "$HOME"/ tmux
stow -vD -t "$HOME"/ user-dirs
stow -vD -t "$HOME"/ zathura
stow -vD -t "$HOME"/ zsh
