stow -vD -t ~/ X11
stow -vD -t ~/ bat
stow -vD -t ~/ bottom
stow -vD -t ~/ broot
stow -vD -t ~/ bspwm
stow -vD -t ~/ dunst
stow -vD -t ~/ dwm
stow -vD -t ~/ flake8
stow -vD -t ~/ git
stow -vD -t ~/ htop
stow -vD -t ~/ lf
stow -vD -t ~/ mpv
stow -vD -t ~/ neofetch
stow -vD -t ~/ nvim
stow -vD -t ~/ polybar
stow -vD -t ~/ pycodestyle
stow -vD -t ~/ pylint
stow -vD -t ~/ ranger
stow -vD -t ~/ rofi
stow -vD -t ~/ shell
stow -vD -t ~/ starship
stow -vD -t ~/ sxhkd
stow -vD -t ~/ tmux
stow -vD -t ~/ user-dirs
stow -vD -t ~/ zathura
stow -vD -t ~/ zsh
