# xdg-mime default  application/gpx+xml
# xdg-mime default  application/gpx+xml
# xdg-mime default  application/gzip
# xdg-mime default  application/gzip
# xdg-mime default  application/javascript
# xdg-mime default  application/javascript
# xdg-mime default  application/json
# xdg-mime default  application/json
# xdg-mime default  application/mbox
# xdg-mime default  application/mbox
# xdg-mime default  application/octet-stream
# xdg-mime default  application/octet-stream
# xdg-mime default  application/pgp-signature
# xdg-mime default  application/sql
# xdg-mime default  application/sql
# xdg-mime default  application/vnd.adobe.flash.movie
# xdg-mime default  application/vnd.kde.kxmlguirc
# xdg-mime default  application/vnd.rar
# xdg-mime default  application/vnd.sqlite3
# xdg-mime default  application/vnd.stardivision.mail
# xdg-mime default  application/vnd.tcpdump.pcap
# xdg-mime default  application/x-awk
# xdg-mime default  application/x-awk
# xdg-mime default  application/x-cdrdao-toc
# xdg-mime default  application/x-desktop
# xdg-mime default  application/x-dia-diagram
# xdg-mime default  application/x-executable
# xdg-mime default  application/x-executable
# xdg-mime default  application/x-font-afm
# xdg-mime default  application/x-font-bdf
# xdg-mime default  application/x-font-tex
# xdg-mime default  application/x-font-tex-tfm
# xdg-mime default  application/x-font-type1
# xdg-mime default  application/x-genesis-rom
# xdg-mime default  application/x-gettext-translation
# xdg-mime default  application/x-glade
# xdg-mime default  application/x-ica
# xdg-mime default  application/x-java-keystore
# xdg-mime default  application/x-java-keystore
# xdg-mime default  application/x-lz4
# xdg-mime default  application/x-m4
# xdg-mime default  application/x-m4
# xdg-mime default  application/x-mimearchive
# xdg-mime default  application/x-mozilla-bookmarks
# xdg-mime default  application/x-mozilla-bookmarks
# xdg-mime default  application/x-ms-shortcut
# xdg-mime default  application/x-msi
# xdg-mime default  application/x-ole-storage
# xdg-mime default  application/x-partial-download
# xdg-mime default  application/x-perl
# xdg-mime default  application/x-perl
# xdg-mime default  application/x-php
# xdg-mime default  application/x-php
# xdg-mime default  application/x-raw-disk-image
# xdg-mime default  application/x-riff
# xdg-mime default  application/x-ruby
# xdg-mime default  application/x-ruby
# xdg-mime default  application/x-sc
# xdg-mime default  application/x-shared-library-la
# xdg-mime default  application/x-sharedlib
# xdg-mime default  application/x-sharedlib
# xdg-mime default  application/x-trash
# xdg-mime default  application/x-trash
# xdg-mime default  application/x-wine-extension-inf
# xdg-mime default  application/x-x509-ca-cert
# xdg-mime default  application/x-yaml
# xdg-mime default  application/x-yaml
# xdg-mime default  application/xml
# xdg-mime default  application/xml-dtd
# xdg-mime default  application/xml-dtd
# xdg-mime default  application/xml-external-parsed-entity
# xdg-mime default  application/xslt+xml
# xdg-mime default  audio/x-mod
# xdg-mime default  font/ttf
# xdg-mime default  font/woff
# xdg-mime default  font/woff2
# xdg-mime default  image/emf
# xdg-mime default  image/vnd.adobe.photoshop
# xdg-mime default  image/vnd.microsoft.icon
# xdg-mime default  image/vnd.zbrush.pcx
# xdg-mime default  image/vnd.zbrush.pcx
# xdg-mime default  image/x-eps
# xdg-mime default  image/x-icns
# xdg-mime default  text/cache-manifest
# xdg-mime default  text/css
# xdg-mime default  text/css
# xdg-mime default  text/csv
# xdg-mime default  text/markdown
# xdg-mime default  text/markdown
# xdg-mime default  text/rust
# xdg-mime default  text/rust
# xdg-mime default  text/troff
# xdg-mime default  text/troff
# xdg-mime default  text/vcard
# xdg-mime default  text/vnd.graphviz
# xdg-mime default  text/x-authors
# xdg-mime default  text/x-authors
# xdg-mime default  text/x-bibtex
# xdg-mime default  text/x-bibtex
# xdg-mime default  text/x-changelog
# xdg-mime default  text/x-changelog
# xdg-mime default  text/x-copying
# xdg-mime default  text/x-copying
# xdg-mime default  text/x-credits
# xdg-mime default  text/x-dbus-service
# xdg-mime default  text/x-dsrc
# xdg-mime default  text/x-emacs-lisp
# xdg-mime default  text/x-emacs-lisp
# xdg-mime default  text/x-gherkin
# xdg-mime default  text/x-go
# xdg-mime default  text/x-go
# xdg-mime default  text/x-idl
# xdg-mime default  text/x-install
# xdg-mime default  text/x-install
# xdg-mime default  text/x-iptables
# xdg-mime default  text/x-ldif
# xdg-mime default  text/x-lua
# xdg-mime default  text/x-lua
# xdg-mime default  text/x-matlab
# xdg-mime default  text/x-matlab
# xdg-mime default  text/x-maven+xml
# xdg-mime default  text/x-microdvd
# xdg-mime default  text/x-microdvd
# xdg-mime default  text/x-ms-regedit
# xdg-mime default  text/x-ms-regedit
# xdg-mime default  text/x-patch
# xdg-mime default  text/x-patch
# xdg-mime default  text/x-python
# xdg-mime default  text/x-python
# xdg-mime default  text/x-python3
# xdg-mime default  text/x-qml
# xdg-mime default  text/x-readme
# xdg-mime default  text/x-readme
# xdg-mime default  text/x-rpm-spec
# xdg-mime default  text/x-rst
# xdg-mime default  text/x-setext
# xdg-mime default  text/x-systemd-unit
# xdg-mime default  text/x-troff-me
xdg-mime default chromium-devel.desktop text/html
xdg-mime default chromium.desktop image/webp
xdg-mime default darktable.desktop image/tiff
xdg-mime default engrampa.desktop application/x-cd-image
xdg-mime default engrampa.desktop application/x-ms-dos-executable
xdg-mime default engrampa.desktop application/zip
xdg-mime default feh.desktop image/x-portable-graymap
xdg-mime default feh.desktop image/x-xbitmap
xdg-mime default firefox.desktop application/x-xpinstall
xdg-mime default gcr-viewer.desktop application/pkix-cert
xdg-mime default gcr-viewer.desktop application/x-pem-key
xdg-mime default gcr-viewer.desktop application/x-x509-ca-cert
xdg-mime default gimp.desktop application/postscript
xdg-mime default gimp.desktop application/postscript
xdg-mime default gimp.desktop image/svg+xml
xdg-mime default gimp.desktop image/svg+xml
xdg-mime default gimp.desktop image/x-xcf
xdg-mime default kde-kview.desktop image/jpeg
xdg-mime default libreoffice-calc.desktop application/vnd.ms-excel.sheet.binary.macroEnabled.12
xdg-mime default libreoffice-calc.desktop application/vnd.ms-excel.sheet.macroEnabled.12
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet
xdg-mime default libreoffice-calc.desktop text/csv
xdg-mime default libreoffice-calc.desktop text/tab-separated-values
xdg-mime default libreoffice-draw.desktop application/vnd.visio
xdg-mime default libreoffice-impress.desktop application/vnd.ms-powerpoint.presentation.macroEnabled.12
xdg-mime default libreoffice-impress.desktop application/vnd.oasis.opendocument.presentation
xdg-mime default libreoffice-impress.desktop application/vnd.openxmlformats-officedocument.presentationml.slideshow
xdg-mime default libreoffice-impress.desktop application/vnd.openxmlformats-officedocument.presentationml.template
xdg-mime default libreoffice-writer.desktop application/vnd.ms-word.document.macroEnabled.12
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text
xdg-mime default mplayer.desktop audio/x-wav
xdg-mime default mupdf.desktop application/epub+zip
xdg-mime default mupdf.desktop application/oxps
xdg-mime default nvim.desktop application/x-shellscript
xdg-mime default nvim.desktop text/x-c++hdr
xdg-mime default nvim.desktop text/x-c++src
xdg-mime default nvim.desktop text/x-chdr
xdg-mime default nvim.desktop text/x-csrc
xdg-mime default nvim.desktop text/x-java
xdg-mime default nvim.desktop text/x-makefile
xdg-mime default nvim.desktop text/x-tcl
xdg-mime default nvim.desktop text/x-tex
xdg-mime default org.pwmt.zathura-ps.desktop image/x-eps
xdg-mime default org.pwmt.zathura.desktop application/pdf
xdg-mime default org.qutebrowser.qutebrowser.desktop application/rdf+xml
xdg-mime default panel-desktop-handler.desktop application/x-desktop
xdg-mime default sxiv-2.desktop image/jpeg
xdg-mime default thunderbird.desktop message/rfc822
xdg-mime default totem.desktop audio/x-mod
xdg-mime default totem.desktop audio/x-musepack
xdg-mime default totem.desktop video/ogg
xdg-mime default totem.desktop video/x-msvideo
xdg-mime default vim.desktop application/x-shellscript
xdg-mime default vim.desktop text/plain
xdg-mime default vim.desktop text/x-c++hdr
xdg-mime default vim.desktop text/x-c++src
xdg-mime default vim.desktop text/x-chdr
xdg-mime default vim.desktop text/x-csrc
xdg-mime default vim.desktop text/x-java
xdg-mime default vim.desktop text/x-makefile
xdg-mime default vim.desktop text/x-tex
xdg-mime default vlc.desktop audio/mpeg
xdg-mime default vlc.desktop video/mp4
xdg-mime default vlc.desktop video/mpeg
xdg-mime default vlc.desktop video/webm
xdg-mime default wine-extension-gif.desktop image/gif
xdg-mime default wine-extension-hlp.desktop application/winhlp
xdg-mime default wine-extension-htm.desktop text/html
xdg-mime default wine-extension-ini.desktop application/x-wine-extension-ini
xdg-mime default wine-extension-png.desktop image/png
xdg-mime default wine-extension-txt.desktop text/plain
xdg-mime default wine-extension-url.desktop application/x-mswinurl
xdg-mime default wine-extension-vbs.desktop application/x-wine-extension-vbs
xdg-mime default wine-extension-xml.desktop application/xml
