[tool.ruff]
line-length = 120
# cache-dir = "~/.cache/ruff"

# On top of the defaults (`E`, `F`), enable flake8-bugbear (`B`) and flake8-quotes (`Q`).
select = ["E", "F", "B", "Q", "W", "C90", "I", "D", "UP", "N", "YTT", "ANN", "S", "BLE", "FBT", "A", "C4", "T10", "EM", "ICN", "T20", "RET", "SIM", "TID", "ARG", "DTZ", "ERA", "PD", "PGH", "PLC", "PLE", "PLR", "PLW", "RUF"]

# Never enforce `E501` (line length violations).
# ignore = ["E501"]

# Always autofix, but never try to fix `F401` (unused imports).
# fix = true
# unfixable = ["F401"]
fixable = ["E", "F"]

# Group violations by containing file.
format = "grouped"

[tool.ruff.flake8-import-conventions.aliases]
altair = "alt"
"matplotlib.pyplot" = "plt"
numpy = "np"
pandas = "pd"
seaborn = "sns"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"

[tool.ruff.flake8-errmsg]
max-string-length = 20

[tool.ruff.flake8-tidy-imports]
# Disallow all relative imports.
ban-relative-imports = "all"

[tool.ruff.isort]
combine-as-imports = true

[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true
