
[env]
TERM = "xterm-256color"

[font]
size = 11
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode NerdFont"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
