# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

[plugins.zsh-colored-man-pages]
github = "ael-code/zsh-colored-man-pages"
[plugins.zsh-command-time]
github = "popstas/zsh-command-time"
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
# [plugins.zsh-fuzzy-search-and-edit]
# github = "seletskiy/zsh-fuzzy-search-and-edit"
[plugins.emoji-cli]
github = "b4b4r07/emoji-cli"
[plugins.forgit]
github = 'wfxr/forgit'
# [plugins.zsh-plugin-fzf-finder]
# github = 'leophys/zsh-plugin-fzf-finder'
[plugins.alias-tips]
github = 'djui/alias-tips'
# [plugins.zsh-interactive-cd]
# github = 'changyuheng/zsh-interactive-cd'
# [plugins.zsh-zoxide]
# github = 'z-shell/zsh-zoxide'
# [plugins.fzf-tab]
# github = 'Aloxaf/fzf-tab.git'
[plugins.ugit]
github = 'Bhupesh-V/ugit'
[plugins.fzf-docker]
github = 'pierpo/fzf-docker'
[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete.git'
# [plugins.fzf-tab-completion]
# github = 'lincheney/fzf-tab-completion'
# [plugins.fzf-zsh-completions]
# github = 'chitoku-k/fzf-zsh-completions'
[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
