# only if interactive shell
[[ $- == *i* ]] && stty -ixon -ixoff # turns off CTRL-S

# some history related settings
HISTFILE=${XDG_CACHE_HOME:-$HOME/.cache}/zhistory       # enable history saving on shell exit
setopt APPEND_HISTORY          # append rather than overwrite history file.
setopt SHARE_HISTORY          # append rather than overwrite history file.
HISTSIZE=12000                 # lines of history to maintain memory
SAVEHIST=10000                 # lines of history to maintain in history file.
setopt HIST_EXPIRE_DUPS_FIRST  # allow dups, but expire old ones when I hit HISTSIZE
setopt EXTENDED_HISTORY        # save timestamp and runtime information
# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"
export ZLE_SPACE_SUFFIX_CHARS='&|'

# if [[ $OSTYPE == linux* ]]; then
if tty -s; then
    # zplug
    export ZPLUG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/zplug"
    source $ZPLUG_HOME/init.zsh
    # zplug "changyuheng/fz", defer:1
    # zplug "rupa/z", use:z.sh
    zplug "ael-code/zsh-colored-man-pages", defer:2
    zplug "popstas/zsh-command-time", defer:2
    zplug "zdharma-continuum/fast-syntax-highlighting", defer:2
    # zplug "mafredri/zsh-async", from:"github", use:"async.zsh"
    zplug "seletskiy/zsh-fuzzy-search-and-edit"
    # zplug "andrewferrier/fzf-z"
    # zplug "gerges/oh-my-zsh-jira-plus", defer:2
    # zplug "micrenda/zsh-nohup", defer:2
    zplug "b4b4r07/emoji-cli", defer:2
    # zplug "MichaelAquilina/zsh-autoswitch-virtualenv", defer:2
    zplug 'wfxr/forgit', defer:2
    # zplug 'jedahan/ripz', defer:2
    # if [ "$OSTYPE" != "linux-android" ]; then
    #     zplug "MichaelAquilina/zsh-you-should-use", defer:2
    # fi
    # # use Alt-e to launch a finder
    zplug 'leophys/zsh-plugin-fzf-finder', defer:2
    # zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
    # zplug "romkatv/powerlevel10k", as:theme, depth:1
    # let zplug manage itself
    zplug 'zplug/zplug', hook-build:'zplug --self-manage'
    # zplug 'NullSense/fuzzy-sys'

    # Install plugins if there are plugins that have not been installed
    if ! zplug check --verbose; then
        printf "Install? [y/N]: "
    if read -q; then
            echo; zplug install
        fi
    fi
    # Then, source plugins and add commands to $PATH
    # zplug load --verbose
    zplug load
fi

test -s /usr/share/fzf/key-bindings.zsh && source "$_" || true
test -s /usr/share/fzf/completion.zsh && source "$_" || true
test -s /usr/share/doc/fzf/examples/key-bindings.zsh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/ssh_agent.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/alias.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/keybinding.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/svn_prompt.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/fuzzy_functions.sh && source "$_" || true
# test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/gruvbox256.sh && source "$_" || true

# enable VI mode
bindkey -v
export KEYTIMEOUT=1
# edit line in vim buffer - ctrl-v
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line
bindkey ' ^?' backward-delete-char

# include host specific settings
test -s ${XDG_CONFIG_HOME:-${HOME}/.config}/zshrc.local && source "$_" || true
test -s ${XDG_CONFIG_HOME:-${HOME}/.config}/broot/launcher/bash/br && source "$_" || true

eval "$(starship init zsh)"
eval "$(zoxide init zsh --cmd cd)"

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if command -v fuck >/dev/null; then
    eval $(thefuck --alias)
    # You can use whatever you want as an alias, like for Mondays:
    eval $(thefuck --alias FUCK)
fi
