# only if interactive shell
[[ $- == *i* ]] && stty -ixon -ixoff # turns off CTRL-S
# stty erase ""
# stty ek

zmodload zsh/zprof

# some history related settings
HISTFILE=${XDG_CACHE_HOME:-$HOME/.cache}/zhistory       # enable history saving on shell exit
setopt APPEND_HISTORY          # append rather than overwrite history file.
setopt SHARE_HISTORY          # append rather than overwrite history file.
HISTSIZE=12000                 # lines of history to maintain memory
SAVEHIST=10000                 # lines of history to maintain in history file.
setopt HIST_EXPIRE_DUPS_FIRST  # allow dups, but expire old ones when I hit HISTSIZE
setopt EXTENDED_HISTORY        # save timestamp and runtime information
export ZLE_SPACE_SUFFIX_CHARS='&|'

# set the terminal title
case ${TERM} in
    xterm*|rxvt*|Eterm|aterm|kterm|gnome*)
        PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
        ;;
    screen*|tmux*)
        PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
        ;;
esac

test -s /usr/share/fzf/key-bindings.zsh && source "$_" || true
test -s /usr/share/fzf/completion.zsh && source "$_" || true
test -s /usr/share/doc/fzf/examples/key-bindings.zsh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/ssh_agent.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/alias.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/keybinding.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/svn_prompt.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/fuzzy_functions.sh && source "$_" || true
test -s ${XDG_CONFIG_HOME:-$HOME/.config}/shell/themes.sh && source "$_" || true

# enable VI mode
bindkey -v
export KEYTIMEOUT=1
# edit line in vim buffer - ctrl-v
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line
bindkey ' ^?' backward-delete-char

# include host specific settings
test -s ${XDG_CONFIG_HOME:-${HOME}/.config}/zshrc.local && source "$_" || true
test -s ${XDG_CONFIG_HOME:-${HOME}/.config}/broot/launcher/bash/br && source "$_" || true

if tty -s; then
    command -v sheldon >/dev/null && eval "$(sheldon source)"
    command -v starship >/dev/null && eval "$(starship init zsh)"
    command -v zoxide >/dev/null && eval "$(zoxide init zsh --cmd cd)"
    command -v direnv >/dev/null && eval "$(zoxide init zsh --cmd cd)"
    # change TAB for zsh-autocomplete (TODO)
    bindkey '\t' menu-select "$terminfo[kcbt]" menu-select
    bindkey -M menuselect '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete
fi

# if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
#     dbus-run-session Hyprland
# fi

zprof > /tmp/zsh.$$
