[manager]
layout         = [ 1, 4, 3 ]
# sort_by        = "modified"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
folder = [
	{ run = 'open -R "$@"', desc = "Reveal in Finder" },
	{ run = '$EDITOR "$@"' },
]
archive = [
	{ run = 'unar "$1"', desc = "Extract here" },
]
text = [
	{ run = '$EDITOR "$@"', block = true },
]
image = [
	{ run = 'open "$@"', desc = "Open" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
	{ run = 'umpv "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
	{ run = 'umpv "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
	{ run = 'open "$@"', desc = "Open" },
	{ run = 'open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },

	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false

[plugin]
previewers = [
  { name = "*/", run = "folder", sync = true },
  { name = "*.md", run = "preview" },
  { name = "*.csv", run = "preview" },
  { mime = "text/*", run = "code" },
	{ mime = "video/*", run = "noop" },
  { mime = "*/xml", run = "code" },
  { mime = "*/javascript", run = "code" },
  { mime = "*/x-wine-extension-ini", run = "code" },
  { name = "*", run = "preview" },
]
prepend_preloaders = [
	{ mime = "video/*", run = "noop" },
]
append_preloaders = [
	{ mime = "video/*", run = "noop" },
]

# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*"
# run  = "git"
#
# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*/"
# run  = "git"
