#!/bin/sh

# The clickable help menu. Middle click to restart wm.

# Determine WM for restart
if pidof dwm >/dev/null; then
	READMEFILE=/usr/local/share/dwm/larbs.mom
	restartwm() { pkill -HUP dwm; }
else
	restartwm() { i3 restart; }
fi

case $BLOCK_BUTTON in
1) groff -mom "${READMEFILE:-${XDG_DATA_HOME:-$HOME/.local/share}/larbs/readme.mom}" -Tpdf | zathura - ;;
2) restartwm ;;
3) notify-send "❓ Help module" "\- Left click to open LARBS guide.
- Middle click to refresh window manager." ;;
6) "${TERMINAL:-wezterm}" -e "$EDITOR" "$0" ;;
esac
echo "❓"
