#!/bin/bash
termux-notification --priority low -t "Phone backup" -c "starting..."
if [ -d "HOME/storage/dcim/Camera/cache" ]; then
    trash "$HOME/storage/dcim/Camera/cache"
fi
rsync -avzO --remove-source-files "$HOME/storage/dcim/Camera/" backup:/mnt/media/photos/todo/photos_from_phone/camera/
rsync -avzO --remove-source-files "$HOME/storage/shared/Download/" backup:/mnt/media/downloads/
rsync -avzO --remove-source-files "$HOME/storage/shared/Movies/" backup:/mnt/media/photos/todo/photos_from_phone/
rsync -avzO --remove-source-files "$HOME/storage/shared/Pictures/" backup:/mnt/media/photos/todo/photos_from_phone/
rsync -avzO --remove-source-files "$HOME/storage/shared/WhatsApp/Media/WhatsApp Documents/" backup:/mnt/media/downloads/
rsync -avzO --remove-source-files "$HOME/storage/shared/WhatsApp/Media/WhatsApp Images/" backup:/mnt/media/photos/todo/photos_from_phone/whatsapp/
rsync -avzO --remove-source-files "$HOME/storage/shared/WhatsApp/Media/WhatsApp Video/" backup:/mnt/media/photos/todo/photos_from_phone/whatsapp/
rsync -avzO --remove-source-files "$HOME/storage/shared/WhatsApp/Media/WhatsApp Voice Notes/" backup:/mnt/media/photos/todo/photos_from_phone/whatsapp/
mkdir -p  "$HOME/storage/shared/"{Download,Music,Movies,Pictures}

#backup - sync content
rsync -avzO --delete  "$HOME/storage/shared/" backup:heiko_phone_huawei/
termux-notification --priority low -t "Phone backup - DONE" -c "<stdin/stderr>"
