# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
#
# TERM
export TERM="xterm-256color"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# some history related settings
HISTFILE=$HOME/.zhistory       # enable history saving on shell exit
setopt APPEND_HISTORY          # append rather than overwrite history file.
setopt SHARE_HISTORY          # append rather than overwrite history file.
HISTSIZE=12000                 # lines of history to maintain memory
SAVEHIST=10000                 # lines of history to maintain in history file.
setopt HIST_EXPIRE_DUPS_FIRST  # allow dups, but expire old ones when I hit HISTSIZE
setopt EXTENDED_HISTORY        # save timestamp and runtime information
# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# zplug
source ~/.zplug/init.zsh
zplug "changyuheng/fz", defer:1
zplug "rupa/z", use:z.sh
if [ "$OSTYPE" != "cygwin" ] ; then
    # zplug "djui/alias-tips", defer:2
    zplug "paulmelnikow/zsh-startup-timer"
    # TODO: messes with right prompt
    # zplug "laurenkt/zsh-vimto"
fi
zplug "ael-code/zsh-colored-man-pages", defer:2
zplug "popstas/zsh-command-time", defer:2
zplug "zdharma/fast-syntax-highlighting", defer:2
# zplug "mafredri/zsh-async", from:"github", use:"async.zsh"
zplug "seletskiy/zsh-fuzzy-search-and-edit"
zplug "andrewferrier/fzf-z"
# zplug "gerges/oh-my-zsh-jira-plus", defer:2
# zplug "micrenda/zsh-nohup", defer:2
zplug "b4b4r07/emoji-cli", defer:2
# zplug "MichaelAquilina/zsh-autoswitch-virtualenv", defer:2
zplug 'wfxr/forgit', defer:2
# zplug 'jedahan/ripz', defer:2
zplug "MichaelAquilina/zsh-you-should-use", defer:2
# use Alt-e to launch a finder
zplug 'leophys/zsh-plugin-fzf-finder', defer:2
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# config for zsh-vimto
export VIMTO_COLOR_NORMAL_TEXT=white
export VIMTO_COLOR_NORMAL_BACKGROUND=yellow

# definitions for powerlevel9k
# POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('status' 'os_icon' 'root_indicator' 'ssh' 'context' 'dir_writable' 'dir' 'virtualenv' 'vcs')
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('background_jobs' 'nvm' 'rvm' 'load' 'ram_joined' 'ip' 'time')

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%{%F{249}%}\u250f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%F{249}%}\u2517%{%F{default}%} "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"
POWERLEVEL9K_TODO_BACKGROUND="black"
POWERLEVEL9K_TODO_FOREGROUND="249"
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="green"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="black"
# POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="249"
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_NVM_BACKGROUND="black"
POWERLEVEL9K_NVM_FOREGROUND="249"
POWERLEVEL9K_NVM_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_RVM_BACKGROUND="black"
POWERLEVEL9K_RVM_FOREGROUND="249"
POWERLEVEL9K_RVM_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="black"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="249"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="249"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="249"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_RAM_BACKGROUND="black"
POWERLEVEL9K_RAM_FOREGROUND="249"
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
POWERLEVEL9K_BATTERY_LOW_BACKGROUND="black"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="black"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="black"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="black"
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="249"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="249"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="249"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="249"
POWERLEVEL9K_BATTERY_LOW_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_BATTERY_CHARGING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_BATTERY_DISCONNECTED_VISUAL_IDENTIFIER_COLOR="249"
POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND="249"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S} \UE12E"

# Then, source plugins and add commands to $PATH
# zplug load --verbose
zplug load

# TODO: generate path name
test -s ~/dotfiles/shell/env.sh && source ~/dotfiles/shell/env.sh || true
test -s ~/dotfiles/shell/functions.sh && source ~/dotfiles/shell/functions.sh || true
test -s ~/dotfiles/shell/ssh_agent.sh && source ~/dotfiles/shell/ssh_agent.sh || true
test -s ~/dotfiles/shell/alias.sh && source ~/dotfiles/shell/alias.sh || true
test -s ~/dotfiles/shell/fuzzy_functions.sh && source ~/dotfiles/shell/fuzzy_functions.sh || true
test -s ~/dotfiles/shell/keybinding.sh && source ~/dotfiles/shell/keybinding.sh || true
test -s ~/dotfiles/zsh/svn_prompt.sh && source ~/dotfiles/zsh/svn_prompt.sh || true
test -s ~/.fzf/shell/key-bindings.zsh && source ~/.fzf/shell/key-bindings.zsh || true
test -s ~/.fzf/shell/completion.zsh && source ~/.fzf/shell/completion.zsh || true

# enable VI mode
bindkey -v
export KEYTIMEOUT=1
# edit line in vim buffer - ctrl-v
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line
bindkey ' ^?' backward-delete-char

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# include host specific settings
test -s ~/.zshrc.local && source ~/.zshrc.local || true

test -s /home/heiko/.config/broot/launcher/bash/br && source /home/heiko/.config/broot/launcher/bash/br || true
