#!/bin/sh

# Prints the current volume or 🔇 if muted.
DEVICE="$(pamixer --list-sinks | grep -v "^Sinks:" | sed 's/.* "\(.*\)" ".*/\1/' | sort | tail -1)"

case $BLOCK_BUTTON in
1) setsid -f "$TERMINAL" -e pulsemixer ;;
2) pamixer --sink "$DEVICE" -t ;;
4) pamixer --sink "$DEVICE" --allow-boost -i 1 ;;
5) pamixer --sink "$DEVICE" --allow-boost -d 1 ;;
3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --sink "$DEVICE" --get-mute) = true ] && echo 🔇 && exit

vol="$(pamixer --sink "$DEVICE" --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon$vol%"
